### ISSUE TITLE
Request: ctrl+d to exit

### ISSUE THREAD

**Issue by AndydeCleyre** [remokasu/stacker#2]
Hello, and thanks for this, it's great!

Many shells can be cleanly quit by hitting ctrl+d, but in stacker it results in a traceback for an `EOFError`, and the shell remains open.

I'm requesting that hitting ctrl+d have the same effect as running "exit"

```python
Stacker 1.4.0 on linux
Type "help" or "help-jp" to get more information.
stacker:0>
[ERROR]:
Traceback (most recent call last):
  File "/home/andy/.local/share/venvs/48d35bf73e41cdf9d060649e4c36c691/venv/lib/python3.10/site-packages/stacker/stacker.py", line 868, in run
    expression = prompt(
  File "/home/andy/.local/share/venvs/48d35bf73e41cdf9d060649e4c36c691/venv/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1410, in prompt
    return session.prompt(
  File "/home/andy/.local/share/venvs/48d35bf73e41cdf9d060649e4c36c691/venv/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1024, in prompt
    return self.app.run(
  File "/home/andy/.local/share/venvs/48d35bf73e41cdf9d060649e4c36c691/venv/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 967, in run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/andy/.local/share/venvs/48d35bf73e41cdf9d060649e4c36c691/venv/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 881, in run_async
    return await _run_async(f)
  File "/home/andy/.local/share/venvs/48d35bf73e41cdf9d060649e4c36c691/venv/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 744, in _run_async
    result = await f
EOFError
stacker:1>
```

**Comment by remokasu** [comment]
Thank you for your valuable feedback and for taking the time to report this issue. I appreciate it!

I have addressed the EOFError issue in the latest commit. Now, hitting Ctrl+D will properly exit the interactive mode of Stacker, just like the "exit" command.
